### ISSUE TITLE
Invalid link notebooks/getting_started.livemd in documentation 

### ISSUE THREAD

**Issue by olmohake** [brainlid/langchain#144]
File has been moved from /notebooks to /guides, however the documentation still points to the old path.

**Comment by brainlid** [comment]
Thanks for pointing this out. I updated the docs and published them. It includes the notebooks in the docs now! :tada: 

More to come, but this resolves this issue and a docs link to `custom_functions.livemd`, both of which were updated.

https://hexdocs.pm/langchain/0.3.0-rc.0/readme.html
