### ISSUE TITLE
TextToTitleChain: Ability to specify min & max length

### ISSUE THREAD

**Issue by cpursley** [brainlid/langchain#163]
I know llms are not great about following length rules, but it would be nice to be able to pass in the preferred lengths to the prompt. Another fallback/alternative would be to check the output length and if too short/long, pass it back to generate another title.

**Comment by brainlid** [comment]
Hi @cpursley! 

I added support for providing examples to the the `TextToTitleChain`. While it's not an explicit length control, examples provide more consistency with style, format, and length. So it has a much better chance of working for this need.

**Comment by cpursley** [comment]
Awesome, thanks!

**Comment by brainlid** [comment]
With this latest PR #216, I added the ability to override the system prompt for the TextToTitleChain, making it easier to control and get what you want.

The docs for the module were updated. Usage looks like this:

```elixir
%{
  llm: llm,
  input_text: user_text,
  override_system_prompt: ~s|
    You expertly summarize the User Text into a short 3 or 4 word title to represent a conversation in a positive way.|
}
|> TextToTitleChain.new!()
|> TextToTitleChain.evaluate()
```
