### ISSUE TITLE
Safety responses for streamed generation for ChatGoogleAI raise exception in complete_final_delta

### ISSUE THREAD

**Issue by elliotb** [brainlid/langchain#189]
If a streaming assistant response for ChatGoogleAI halts due to a safety issue, the complete_final_delta call raises an exception as it's expecting a MessageDelta to update, but instead the last item in the last list is an error tuple.

It raises `** (BadMapError) expected a map, got: {:error, "Unexpected response"}`

The data passed to it comes in this shape:

```
[
  [
    %LangChain.MessageDelta{
      content: "[redacted]",
      status: :incomplete,
      index: nil,
      role: :assistant,
      tool_calls: nil
    }
  ],
  [error: "Unexpected response"]
]
```

The unexpected response comes from the fallback `do_process_response`, where the inspect of `other` looks like:

`%{"avgLogprobs" => "NaN", "finishReason" => "SAFETY", "safetyRatings" => [%{"blocked" => true, "category" => "HARM_CATEGORY_HATE_SPEECH", "probability" => "LOW"}, %{"category" => "HARM_CATEGORY_DANGEROUS_CONTENT", "probability" => "NEGLIGIBLE"}, %{"blocked" => true, "category" => "HARM_CATEGORY_HARASSMENT", "probability" => "MEDIUM"}, %{"category" => "HARM_CATEGORY_SEXUALLY_EXPLICIT", "probability" => "NEGLIGIBLE"}]}`

i.e. there is a finishReason, but no content or index key present.

It would probably make sense to have a version of  `do_process_response` that handles streamed messages that have a finishReason without content (including other finish reasons that trigger similar issues, such as MALFORMED_FUNCTION_CALL that are handled in #188), but how should these errors then be passed back up to handle within applications?

At the moment any error tuple that is returned within do_process_response for a streamed response will raise an exception like `** (BadMapError) expected a map, got: {:error, "Unexpected response"}`, but it feels like we should be handling these and perhaps firing a callback. What are your thoughts?

**Comment by brainlid** [comment]
Has this been handled now through your PR #188 or PR #186? I'm guessing this is safe to close now.
