### ISSUE TITLE
Implement the Router chain

### ISSUE THREAD

**Issue by brainlid** [brainlid/langchain#29]
The router chain (documented and implemented in Python version), uses classification and branching to change paths for the following prompts.

https://python.langchain.com/docs/modules/chains/foundational/router

Something I want the router to do is support bringing in different functions based on the context. I may have a LOT of potential functions that the LLM could have access to, but I don't want to clutter it and use up tokens when they aren't relevant to the current goal/context. So routing offers a good way for conditionally bringing in other behaviors/functions.

**Comment by chrisgreg** [comment]
If you have something like a map of routes which has an associated prompt value, I think you’d need some sort of function to inject a message and tell the LLM that the answer to the next chain must be one of the routes that you’ve defined then you pick up the value of that route and use that as the next chain. 

I.e. 
```elixir
%{
  "cats" => "What are three cat breeds", 
  "dogs" => "What are three dog breeds"
 }

query = "Which of these animals meows?"
```

You'd need to tell the LLM to answer with cats or dogs then based on that answer, fetch the query associated (or next chain) and execute that as the next part of the chain.

**Comment by brainlid** [comment]
We might want to setup a struct for map for more context than just the prompt. For instance:

```elixir
%{
  "cats" => %{prompt: "What are three cat breeds", functions: [...cat related functions...]},
  "dogs" => %{prompt: "What are three dog breeds", functions: [...dog related functions...]},
 }
```

**Comment by chrisgreg** [comment]
Yeah absolutely would. To keep it branching you'd want a struct that could handle either a prompt + functions or another set of routes too.

**Comment by brainlid** [comment]
Ah true. Good point. Further branching possibilities.

**Comment by brainlid** [comment]
@chrisgreg I recently started a new Agent that would work better using a router so I started looking into this.

Currently I don't see a good use-case for a multi-stage router. Here's how it works:

1. User asks a question
2. Run the LLM on the question to classify it
3. Use the desired prompt based on the classification and re-run the user's question.

The idea is it isn't re-asking for more information along the way. So it wouldn't be refining it to a more specific branch.

A lot of this comes down to the use-case. If it's a conversation with an Agent, then it could be a multi-step process with the agent to narrow down to exactly what best fits the user's desired topic where the Agent asks additional questions, etc. The Agent could even confirm the topic selection like, "To confirm, you want to talk about mental health issues, specifically social anxiety. Is that correct?"

The structure of the hidden choices could be a tree:

- Mental health
  - depression
  - anxiety
  - dementia
  - bipolar
  - general
- Physical health
  - arthritis or joint issues
  - weight
  - diabetes
  - general

Then it could make a single branch jump.

However, if it's more of a one-shot question -> answer, then there may be no additional classification.

What options are you imagining for having additional sets of routes?

**Comment by chrisgreg** [comment]
I imagined something similar to this example but I agree it may not be needed given what can be done with functions. Maybe it isn't required. But it would be nice to be able to get metadata on the "choices" made - i.e. classifying with each branch and being able to store that for analysis.

**Comment by brainlid** [comment]
This is now implemented. 

https://github.com/brainlid/langchain/blob/main/lib/routing/prompt_route.ex

**Comment by chrisgreg** [comment]
This is fantastic @brainlid ! ❤️ 

Just to be clear - unsure from the docs - are you able to have nested routes? I.e. one route goes down the blog post route - can it then be faced with another set of routes and determine which type of blog post to write and use a different chain for that?
