### ISSUE TITLE
Support Bard LLM

### ISSUE THREAD

**Issue by brainlid** [brainlid/langchain#6]
Add support for the Bard LLM.

**Comment by brainlid** [comment]
I've done some research and since Bard is currently considered a limited release service, there is no official released API. However, there is an unofficial Python package that reverse engineered the API but requires the user to pull the Google cookie from their browser session.

Since it's an unofficial approach and the cookie method is a dirty hack, no one should try to build a production system using it at this time.

**Result**: Waiting for an official API from Google.

Resources:
- https://www.33rdsquare.com/what-is-google-bard-api-how-to-use-it-the-complete-guide/ - Article and background on the situation and usage of the package.
- https://github.com/dsdanielpark/Bard-API - Python packag

**Comment by michaelhakansson** [comment]
> @brainlid It looks like Gemini is ready to be supported. They just released API access today.
> 
> https://ai.google.dev/tutorials/rest_quickstart

And Gemini is now in LangChain: https://github.com/langchain-ai/langchain/pull/14621

**Comment by brainlid** [comment]
Nice!

**Comment by jadengis** [comment]
I'm working to add Gemini support to this library in my own fork. I'm trying to get it working today or tomorrow without streaming.

**Comment by jadengis** [comment]
I've got non-streamed responses, streamed responses and function calls all working in my fork. Just working on adding a few tests and will post a PR for this soon (likely tomorrow). Would love some feedback on the approach or some potential improvements.

There were some quirks getting this to work because the behavior of Google's API is slightly different.

**Comment by brainlid** [comment]
Very cool @jadengis! I haven't had time to look at it yet, but that's awesome.

**Comment by brainlid** [comment]
Closing this as we now have support for Google's API based model Gemini Pro.
