### ISSUE TITLE
Request for Community ChatModel: ChatOllama

### ISSUE THREAD

**Issue by theaveasso** [brainlid/langchain#67]
I am interested in using the ollama as a self hosted llm model in the Elixir Langchain project. I was wondering if it's possible to extend the support to include ChatModel.ChatOllama as well.

Detail: 
[Python langchain_community.chat_models.ChatOllama](https://api.python.langchain.com/en/stable/chat_models/langchain_community.chat_models.ollama.ChatOllama.html#langchain_community.chat_models.ollama.ChatOllama)

Request:
I kindly request the community's assistance or guidance on how to integrate ChatOllama into the Langchain project. I am new to Elixir, (no idea what I am doing most of the time) but I am eager to learn and contribute to this exciting project.

**Comment by acalejos** [comment]
Correct me if I'm wrong @brainlid , but it seems that you just need to implement Ollama as a struct that implements a `call` function the same as the OpenAI one defined [here](https://github.com/brainlid/langchain/blob/d9fc6a088a53b55d0791252150893a843d9fb66a/lib/chat_models/chat_open_ai.ex#L177) .

There seems to be 2 Ollama Elixir clients [as listed on Hex.pm](https://hex.pm/packages?search=ollama&sort=recent_downloads), but both seem pretty new and in their infancy. You could always roll your own or refer directly to the [Ollama REST API](https://github.com/jmorganca/ollama/blob/main/docs/api.md).  You would use these to hit the API endpoints for chat completion etc. as is done with the OpenAI implementation.

Whether or not the models support `Functions` within the context of Langchain and in the same manner as supported through OpenAIs models are a different problem though, so those parts of the implementation might have to be sorted out differently. 

Once you implement this, then you could simply call the new model as your llm:
```elixir
alias LangChain.Chains.LLMChain
alias LangChain.ChatModels.ChatOpenAI
alias LangChain.Message

{:ok, _updated_chain, response} =
  %{llm: ChatOllama.new!(%{model: "llama2"})}
  |> LLMChain.new!()
  |> LLMChain.add_message(Message.new_user!("Testing, testing!"))
  |> LLMChain.run()

response.content
```

Again, this is just the approach I would take, but having not contributed to this library I could be wrong about the requirements for implementing a new model.
