### ISSUE TITLE
Add support for Mistral API

### ISSUE THREAD

**Issue by michalwarda** [brainlid/langchain#77]
As Mistral is starting to show newer and newer models I thought it would be nice to use them through [their API](https://docs.mistral.ai/api/)https://docs.mistral.ai/api/). PR #76 adds this. It supports both streaming and non streaming, and all the parameters.

**Comment by brainlid** [comment]
That's cool. I've got Mistral working through Bumblebee but waiting for a new bumblebee release first. 

Using their API is another option. I'm open to PRs for it.

**Comment by brainlid** [comment]
Related to issue #26

**Comment by brainlid** [comment]
Support was added in https://github.com/brainlid/langchain/pull/76. Merged.
